### ISSUE TITLE
Include per-page scss?

### ISSUE THREAD

**Issue by ftab** [toshimaru/jekyll-include_sass#6]
What I'm hoping to do is include a page-specific SCSS file in the head (critical above-the-fold CSS I've manually crafted)

In my layout file in the head tags:
```
{% if page.critical_css %}
<style type="text/css">
<!--
{% include_sass {{ page.critical_css }} %}
-->
</style>
{% endif %}
```

with each page naming its own, like so:
```
---
layout: default
critical_css: index.scss
---
```

I get an error saying this is invalid, and I have to explicitly specify index.scss or whatever in the layout file. Am I doing it wrong?

The alternative, I guess, is put a style tag and include the sass inside the body of each file

**Comment by toshimaru** [comment]
How about this?

```erb
{% if page.critical_css %}
<style type="text/css">
{% include_sass page.critical_css %}
</style>
{% endif %}

**Comment by ftab** [comment]
Same error:
```
  Liquid Exception: invalid! in /_layouts/default.html
             Error: invalid!
```

**Comment by toshimaru** [comment]
This gem is created for "SASS/SCSS", please use either `.sass` or `.scss`. The error says your file extension is not sass/scss.
https://github.com/toshimaru/jekyll-include_sass/blob/a4843db0c690a2dd2b60423ed85836164ca8cfb8/lib/jekyll/tags/include_sass.rb#L9-L16

**Comment by ftab** [comment]
Yes, I am naming a page variable like this in index.html:

`critical_css: index.scss`

and I want it to include that filename. I thought I could include it dynamically like I can with regular `{% include {{ variable }} %}` statements. So I was expecting `{% include_sass {{ page.critical_css }} %}` to resolve to `{% include_sass index.scss %}` therefore giving it the proper file extension that it's looking for.

It sounds like the plugin is not meant to process dynamic includes. I've worked around it for now by just starting every page like this:

```
---
layout: default
---
<style type="text/css">
<!--
{% include_sass index.scss %}
-->
</style>
```

instead of defining a critical_css variable to tell it which file to use.

It's not ideal, because it puts this in the body, and the browser starts rendering plain text before it processes that, which seems to be fixed if the critical CSS section is in the head

**Comment by toshimaru** [comment]
I've looked into the issue. I'd say **using variable is currently not supported**.

---

NOTE: by using `context`, variable might be available.

```
> context["page.additional_sass"]
=> "additional_sass.sass"
```

https://stackoverflow.com/questions/7919644/using-liquid-variables-inside-of-a-liquid-tag-call

**Comment by ftab** [comment]
I wasn't able to read any context variables like that through the Liquid tag. Instead, I've looked at how Jekyll does variables for the include tag that this is based on, and from the looks of it, the change is simple. I've submitted a PR that will make the syntax I referenced in the original post work, as it does with the normal include tags.
